SilverStripe\View\SSViewer:
  themes:
    - 'cdpa'
    - '$default'
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.lifterClassCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "lifterClassCache"
